# Generated by Django 2.0.1 on 2020-07-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20200703_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdopedido',
            options={'verbose_name': 'Itens do Pedido'},
        ),
        migrations.AlterField(
            model_name='itemdopedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
