# Generated by Django 2.0.1 on 2020-07-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20200703_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parametro nfe'), ('permissao2', 'Permissao 2'), ('permissao3', 'Permissao 3'))},
        ),
    ]
