# Generated by Django 2.0.1 on 2020-07-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20200704_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parametro nfe'), ('ver_dashboard', 'Pode visualizar o dashboard'), ('permissao3', 'Permissao 3'))},
        ),
    ]
