# Generated by Django 2.0.1 on 2020-07-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_auto_20200704_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdopedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens dos Pedidos'},
        ),
    ]
