# Generated by Django 2.0.1 on 2020-07-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200703_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar Clientes'),)},
        ),
    ]
